[package]
name = "natpmp-setup"
version = "0.1.0"
authors = ["navysky <navysky12@pm.me>", "FuseTim <fusetim@gmx.com>"]
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
natpmp = "0.4.0"
anyhow = "*"
